FORMAT: 1A


# Indigen API

Indigen API is api for Indigen


# Group Users

Resource related to user


## Users Collection [/api/v1/users/]


### List All Users [GET]

+ Response 200 (application/json)

        [
            {
                "username":"1842342134",
                "nickname":"tom"
            },
            {
                "username":"18423432222",
                "nickname":"tomson"
            },
            
        ]

### Create new User, Register a new User [POST]

this is register api

+ telephone(string)
+ nickname(string)
+ password(string)
+ country(string)
+ captcha(string)

+ Request  (application/json)

        {
            "telephone":"13177979839",
            "nickname":"tom",
            "password":"nopassword",
            "captha":"135214",
            "country":"泰国",
        }


+ Response 201 (application/json)
    
        {
            "telephone":"13177979839",
            "nickname":"tom",
            "password":"nopassword",
            "captha":"135214",
            "country":"泰国",
        }

+ Response 400 (application/json)

        {
            "errors": 
            {
                "telephone": [
                "telephone already exists, you can login directly"
                ]
            },
            "message": "can not register user using received data"
        }

## Users [/api/v1/users/{user_id}/]

+ Parameters
    + user_id (string) - ID of the User in the form of an integer


### View a User Detail [GET]

+ Response 200 (application/json)

        {
            "telephone":"13177979839",
            "nickname":"tom",            
        }

## User Login [/api/v1/login/]

### user login [POST]

+ username(string)
+ password(string)

+ Request  (application/json)

        {
            "username":"yourusername",
            "password":"yourpassword"
        }

+ Response 200 (application/json)

        {
            "username": "user3",
            "email": null,
            "last_login": "2015-07-28T11:00:12Z",
            "telephone": null,
            "location_country": null,
            "location_city": null,
            "nickname": null,
            "avatar": null,
            "live_start_year": 0,
            "is_male": null,
            "birthday": null,
            "introduction": null,
            "reply_average_second": null,
            "token"
        }


+ Response 400 (application/json)

        {
            "message":"username or password is error"
        }

## Get Login User Profile [/api/v1/profile/]

### Get Login User Profile [GET]

+ Response 200 (application/json)

        {
            "username": "user3",
            "email": null,
            "last_login": "2015-07-28T11:00:12Z",
            "telephone": null,
            "location_country": null,
            "location_city": null,
            "nickname": null,
            "avatar": null,
            "live_start_year": 0,
            "is_male": null,
            "birthday": null,
            "introduction": null,
            "reply_average_second": null
        }

+ Response 400 (application/json)

        {
            "message": "can not access your profile, login first"
        }

# Group Locations

About country, city

## Country Collection [/api/v1/countrys/]

### Get Country List [GET]

+ Response 200 (application/json)

        [
            {
                "name":"中国",
                "telephone_prefix":"86",                
            },
            {
                "name":"美国",
                "telephone_prefix":"1"
            }
        ]


# Group File

## Upload Files Test[/api/v1/upload_file/]

### upload a file [PUT]

