FORMAT: 1A


# Indigen API

Indigen API is api for Indigen


# Group Users

Resource related to user


## Users Collection [/api/v1/users/]


### List All Users, you should be administrator [GET]

+ Response 200 (application/json)

        {
          "count": 40,
          "next": null,
          "previous": null,
          "results": [
            {
              "full_name": null,
              "name": "中国",
              "telephone_prefix": "86",
              "capital_city": null
            },
            {
              "full_name": null,
              "name": "新加坡",
              "telephone_prefix": "65",
              "capital_city": null
            },
            {
              "full_name": null,
              "name": "韩国",
              "telephone_prefix": "82",
              "capital_city": null
            },
          ]
        }

### Create new User, Register a new User [POST]

this is register api

+ register_telephone(string)
+ nickname(string)
+ password(string)
+ register_country(string)
+ captcha(string)

+ Request  (application/json)

        {            
            "nickname":"tom",
            "password":"nopassword",
            "captha":"135214",
            'register_country':'中国',
            'register_telephone':'123212313',
        }


+ Response 201 (application/json)
    
        {            
            "nickname":"tom",
            "password":"nopassword",
            "captha":"135214",
            'register_country':'中国',
            'register_telephone':'123212313',
        }

+ Response 400 (application/json)

        {
            "errors": 
            {
                "register_telephone": [
                "telephone already exists, you can login directly"
                ]
            },
            "message": "can not register user using received data"
        }


## Update uesr's password [/api/v1/users/password/]

### Update user's password [PUT]

+ Request  (application/json)
        
        {
            "old_password":"thisisoldpasswordvalue",
            "new_password":"thisisnewpasswordvalue"
        }

+ Response 200 (application/json)

        {
            "message":"update success"
        }

+ Response 400 (application/json)        

        {
            "message":"error",
            "errors":
            {
                "old_password": [
                  "old_password is error"
                ],
                "new_password": [
                  "new_password can not be blank"
                ],
            }
        }

## Users [/api/v1/users/{user_id}/]

You need to be userself or administrator

+ Parameters
    + user_id (string) - ID of the User in the form of an integer


### View a User Detail [GET]

+ Response 200 (application/json)

        {
            "register_telephone":"13177979839",
            "nickname":"tom",            
        }

## User Login [/api/v1/login/]

### user login [POST]

+ username(string)
+ password(string)

+ Request  (application/json)

        {
            "username":"yourusername",
            "password":"yourpassword"
        }

+ Response 200 (application/json)

        {
            "username": "user3",
            "email": null,
            "last_login": "2015-07-28T11:00:12Z",            
            "token": "11277e8b3b245a7d19b72542e4fec31fbfd86052"
        }


+ Response 400 (application/json)

        {
            "message":"username or password is error"
        }

## Get Login User Profile [/api/v1/profile/]

### Get Login User Profile [GET]

+ Response 200 (application/json)

        {
            "username": "user3",
            "email": null,
            "last_login": "2015-07-28T11:00:12Z",            
        }

+ Response 400 (application/json)

        {
            "message": "can not access your profile, login first"
        }

### Update User Profile [PUT]

+ service_introduction(string)
+ is_male(boolean)
+ age(string)

+ Request  (application/json)
        
        {        
          'is_male':1,
          'age':'90后',
          'avatar_url':"/files/documents/2015/08/07/photo-592-mohu-bigger-15.jpg",
          'personal_statement':'我的服务非常好，哈哈',


          'vocation_type':'留学生',
          'languages':[
          ],
          'native_province':'浙江省',
          'native_city':'杭州市',

          'vocation_name':'职业',                  
          'hobbies':[],
          'characters':[],

          'verify_country': '泰国',
          'verify_city':'曼谷',
          'verify_telephone':'15124131',
          'live_start_year':1,
          'id_card_url':"/files/documents/2015/08/07/photo-592-mohu-bigger-15.jpg"

        }

+ Response 200 (application/json)
        
        {        
          'is_male':1,
          'age':'90后',
          'avatar_url':"/files/documents/2015/08/07/photo-592-mohu-bigger-15.jpg",
          'personal_state':'我的服务非常好，哈哈',


          'vocation_type':'留学生',
          'languages':[
          ],
          'native_province':'浙江省',
          'native_city':'杭州市',

          'vocation_name':'职业',                  
          'hobbies':[],
          'characters':[],
          
          'verify_city':'纽约',
          'live_start_year':1,
          'id_card_url':"/files/documents/2015/08/07/photo-592-mohu-bigger-15.jpg"
        }

+ Response 400 (application/json)

        {
          'message': 'can not update the profile',          
        }        

# Group Locations

About country, city

## Country Collection [/api/v1/countrys/]

### Get Country List, you also can sort countrys list add ?ordering=telephone_prefix to the end url. You may also specify reverse orderings by prefixing the field name with '-', like so /api/v1/countrys/?ordering=-telephone_prefix [GET]

+ Response 200 (application/json)

        {
          "count": 40,
          "next": null,
          "previous": null,
          "results": [
            {
              "full_name": null,
              "name": "中国",
              "telephone_prefix": "86",
              "capital_city": null
            },
            {
              "full_name": null,
              "name": "新加坡",
              "telephone_prefix": "65",
              "capital_city": null
            },
            {
              "full_name": null,
              "name": "韩国",
              "telephone_prefix": "82",
              "capital_city": null
            },
          ]
        }






